groups:
  - name: node_status
    rules:
      - record: node_list
        expr: |
          sum(
            label_replace(up{job="juneogo"} == 0, "status", "down", "", "") or 
            label_replace(juneomcn_P_percent_connected{job="juneogo"}, "status", "up", "", "")
          ) by (server, status)
      
      - record: node_list_low_space
        expr: |
          min by (server) (
            label_replace(
              node_filesystem_avail_bytes{fstype!="tmpfs"} / 1e9 < 20, 
              "status", 
              "low_space", 
              "", 
              ""
            )
          )

  - name: logging_alerts
    rules:
      - alert: HighErrorRate
        expr: |
          sum by (container_name) (
            rate({job="containerlogs"} |~ "(?i)(error|fatal|panic)" [5m])
          ) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate in container {{ $labels.container_name }}"
          description: "Container {{ $labels.container_name }} is generating errors at {{ $value }} per second"

      - alert: LogVolumeSpike
        expr: |
          sum by (container_name) (
            rate({job="containerlogs"}[5m])
          ) > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Log volume spike in {{ $labels.container_name }}"
          description: "Container {{ $labels.container_name }} log volume is {{ $value }} logs/sec"