server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  - job_name: juneogo_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: juneogo
          __path__: /var/log/juneogo/*.log
    
    pipeline_stages:
      - regex:
          expression: '\[(?P<timestamp>[^\]]+)\] (?P<level>[A-Z]+) (?P<message>.*)'
      - timestamp:
          format: '2006-01-02T15:04:05.000Z'
          source: timestamp
      - labels:
          level:
      - output:
          source: message